name: Pull Image from SWR Demo
on:
  push:
    branches:
       master
env:
  REGION_ID: 'cn-north-4'   # example: cn-north-4
  IMAGE_URL: 'swr.cn-north-4.myhuaweicloud.com/actions/swr-test:72114e1d1898dcaed2935ae34bf74a3ada6dd447'     # 镜像地址
jobs:
  swr-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: ${{ env.REGION_ID }}  

      - name: Pull Image from Huawei Cloud SWR
        id: pull-image
        run: |
          docker pull ${{ env.IMAGE_URL }}
