name: Pull Image from SWR Demo
on:
  push:
    branches:
       master
env:
  REGION_ID: '<region id>'   # example: cn-north-4
  IMAGE_URL: '<image url>'     # 镜像地址
jobs:
  swr-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.0.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: ${{ env.REGION_ID }}  

  swr-pull:
    needs: swr-login
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image from Huawei Cloud SWR
        id: pull-image
        env:
        run: |
          docker pull ${{ env.IMAGE_URL }}